### ISSUE TITLE
Files excluded in .rubocop.yml are still evaluated

### ISSUE THREAD

**Issue by timriley** [ashfurrow/danger-rubocop#17]
Hi there,

Over in #11 (hi @gaugau, @ashfurrow), the way that `rubocop` was invoked was changed back to having a list of files explicitly passed to it.

I know you've long since merged this PR, but I'm wondering why this change was made? As far as I'm aware, the previous behaviour should've been already excluding files that were not changed in the current PR.

The problem with this change here is that because the files to lint are now being explicitly passed to the `rubocop` command, `Exclude` rules in `.rubocop.yml` are ignored – if any excluded file is passed explicitly, it then gets evaluated by Rubocop.

The result of this is that files we've chosen to exclude end up being run, and because they're usually excluded for a reason, end up spewing a lot of errors.

This was something I fixed back in #7, and I'd love to see this behaviour restored.

Would you be open to changing this back somehow?

Thanks!

**Comment by timriley** [comment]
(Looking at the PRs a little more closely, I'm not sure if #11 actually actually changed any end-behaviour at all? Was there something about the implementation in #7 that wasn't working? If so, I'd love to hear what it is, and see if we can find a way to fix it while keeping the respect for the `.rubocop.yml` `Exclude` rules)

**Comment by timriley** [comment]
Back again 😬 

Looks like the `--force-exclusion` stuff in #15 actually takes care of this, so I'll close this issue now. Sorry for the noise!

My only comment would be that, to me, setting `force_exclusion` to `true` by default would make a lot of sense. It'd preserve the behaviour we released in #7 (which I think is the right default behaviour) while still allowing people to opt out of it if they really wanted.

@ashfurrow, if that feels good to you, I'll make a PR for that.

**Comment by ashfurrow** [comment]
Sounds great! Just let me know what I can do the help 👍
