### ISSUE TITLE
Question: Lint do not add fail to danger

### ISSUE THREAD

**Issue by javierg** [ashfurrow/danger-rubocop#18]
Maybe I don't get it how to work, but running the Rubocop lint will adding the violations as a message table will not make the Travis build fail.

I made a change to optionally send  `fail` commands to danger for each violation, but I think I am missing something

**Comment by ashfurrow** [comment]
Hmm, this sounds like something we should probably allow users to customize. What do you think that should look like? A PR would be awesome, if you're available.

**Comment by ashfurrow** [comment]
Going to close due to lack of activity – please re-open if this is still a problem.

**Comment by javierg** [comment]
Oh, sorry have been a little bussy I did a fork and did a branch with a change to handle it... will do the PR agains this repo this week, to see what do you think... thanks

**Comment by ashfurrow** [comment]
Awesome, looking forward to it 👍
