### ISSUE TITLE
warnings on changed code only while using inline_comment:true

### ISSUE THREAD

**Issue by benyitzhaki** [ashfurrow/danger-rubocop#28]
Hi,
when using the lint with "inline_comments" flag, it produces warnings on the changed **code** as inline comment + other warnings on the changed **files** as general comment.
I would like to be able to exclude the warning that have not been added as comments on the code (or in other words, exclude warnings on the changed files, only include warnings on the changed code on those files).

this is how i'm using the plugin
`rubocop.lint(inline_comment:true)`

any ideas?
thanks

**Comment by ashfurrow** [comment]
Hmm! What an interesting question. Nothing comes to mind... can you be more specific in your example? What kind of file-specific warnings are you trying to filter out? A screenshot of the problem would be super-helpful here 👍

**Comment by benyitzhaki** [comment]
Sure, attached a screenshot that might explain it better.
As we can see, it added a single comment with an issue that is relevant to the changes i made in the code, however, additional 70+ warnings on the modified files, regardless if i changed the relevant code or not. btw, the single comment that was added as inline comment, doesn't exist in the list of 70+ warnings, therefore, the plugin already knows to filter out only the relevant warnings, however, it doesn't omit the rest of them. I would like to see only the single warning that was relevant to my code..
![Screen Shot 2019-06-26 at 9 52 55](https://user-images.githubusercontent.com/2536651/60157791-3fd33280-97f8-11e9-9fe6-ade57e0ba70f.png)

**Comment by ashfurrow** [comment]
Ah gotcha, so it's leaving _both_? That's weird. Can you confirm your Danger version? I'm happy to look into this further, but I won't have time until this weekend. The [code is here](https://github.com/ashfurrow/danger-rubocop/blob/master/lib/danger_plugin.rb), any insights (or PRs!) you could offer in the meantime would be helpful :bow:

**Comment by benyitzhaki** [comment]
awesome thanks, 
using danger 6.0.9
