### ISSUE TITLE
No source for 0.7.1

### ISSUE THREAD

**Issue by telyn** [ashfurrow/danger-rubocop#36]
Hiya - I notice that there's a release 0.7.1 on rubygems.org but the version in master of this repo is still 0.7.0.

Have you moved the repository somewhere else or just not pushed?

Only reason I ask is I'd like to open a PR for a new feature but having an up-to-date upstream would be best!

**Comment by ashfurrow** [comment]
Looks like 0.7.1 included on this change: https://github.com/ashfurrow/danger-rubocop/pull/33

I forgot to push to the `master` branch (but did remember to push the `0.7.1` tag, at least 😅). That's been pushed now, thanks for letting me know!!

**Comment by telyn** [comment]
No worries - that kinda stuff happens to all of us 😄
