### ISSUE TITLE
Rubocop 0.75 gives 'invalid option: --only-recognized-file-types'

### ISSUE THREAD

**Issue by addhyanmalhotra** [ashfurrow/danger-rubocop#53]
![image](https://user-images.githubusercontent.com/56017810/124088173-4e502680-da70-11eb-99af-c547b2a42e3f.png)

**Comment by ashfurrow** [comment]
Thanks for the issue. The minimum supported version for Rubocop is currently 1.0, so you'll need to upgrade:

https://github.com/ashfurrow/danger-rubocop/blob/91801f5fdf5a155f9b48a775dfe84d8c792d261d/danger-rubocop.gemspec#L21

You could also use an older version of this library. Have a good day!
