### ISSUE TITLE
Discussion: Linting whole file versus linting changes?

### ISSUE THREAD

**Issue by futureperfect** [ashfurrow/danger-rubocop#9]
I'm currently working on a large collection of established Rails services where there's enough violations that raising all of them even just within a normal PR's files is overwhelming to the developer. I try to avoid codebase churn as an artifact of just wholesale style cleanup preferring in most cases to just fix it when you touch it.

With that in mind:

1. Have you given any thought to scoping rubicon violations just to changed lines? If so, do you have a strategy in mind?
1. Would you be amenable to accepting a PR that introduced that change?

I've given some cursory thought to how to go about doing so, but I'm still trying to grok the affordances the git model has in terms of getting lines changed rather than just files changed.

**Comment by ashfurrow** [comment]
I've not considered this, but I think it would make a great addition. I'd love to review a PR together that adds that, let me know what I can do to help :bow:

**Comment by michaelherold** [comment]
I really like this idea. I currently use [rubocop-git](https://github.com/m4i/rubocop-git) to do this, but it's been lagging behind on supporting newer Rubocop versions. Perhaps it will be helpful for  you?

**Comment by RestlessThinker** [comment]
@michaelherold @ashfurrow  I also had this issue when starting to use Danger. We use [Pronto](https://github.com/mmozuras/pronto), which allows us to use rubocop and other runners for JS, SASS. I wrote a pronto plugin that by default will lint added + modified files. It's inspiration is from this plugin! https://github.com/RestlessThinker/danger-pronto

**Comment by gaugau** [comment]
@ashfurrow  We have made a patch for this here https://github.com/ashfurrow/danger-rubocop/pull/11

Please take a look. 
Cheers,

**Comment by ashfurrow** [comment]
Thank you for your contribution @gaugau, I've merged you PR and released it as version 0.4.0 of this gem. 

I'm going to close this issue, if there's still a problem, comment and we can reopen it.
